# Generated by Django 3.2.4 on 2021-07-23 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_alter_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='About')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.person')),
            ],
        ),
    ]
