# Generated by Django 3.2.4 on 2021-07-24 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_person_photo'),
        ('school', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(null=True, to='school.Course', verbose_name='Courses')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.person', verbose_name='Person')),
            ],
        ),
    ]
