# Generated by Django 3.2.4 on 2021-07-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='school.Course', verbose_name='Courses'),
        ),
    ]
