# Generated by Django 3.2.4 on 2021-07-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name'),
        ),
    ]
