# Generated by Django 3.2 on 2021-06-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='im',
            field=models.CharField(max_length=11, unique=True, verbose_name='Inscrição Municipal'),
        ),
    ]
