# Generated by Django 3.2 on 2021-06-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialschool', '0002_auto_20210608_0243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
