# Generated by Django 3.2 on 2021-06-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialschool', '0004_course_coursecategory_group_groupconfig_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
