# Generated by Django 3.2 on 2021-06-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialschool', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='vacancies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
