# Generated by Django 3.2 on 2021-06-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialschool', '0006_auto_20210611_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='student/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
