# Generated by Django 3.2 on 2021-06-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_andress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Andress',
        ),
    ]
