# Generated by Django 3.2 on 2021-06-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='im',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Inscrição Municipal'),
        ),
    ]
