# Generated by Django 3.2 on 2021-06-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_im'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='corporate_function',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secundary', 'Secundary')], max_length=9),
        ),
    ]
