# Generated by Django 3.2 on 2021-06-09 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_username'),
        ('company', '0003_alter_company_corporate_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('type', models.CharField(blank=True, choices=[('employee', 'Employee'), ('voluntary', 'Voluntary')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='accounts.profile')),
            ],
        ),
    ]
