# Generated by Django 3.2 on 2021-06-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=80)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
            ],
        ),
    ]
