# Generated by Django 3.2.4 on 2021-07-21 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Andress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('other', 'Other')], default='residential', max_length=12)),
                ('zip_code', models.CharField(blank=True, max_length=8)),
                ('street', models.CharField(blank=True, max_length=80)),
                ('number', models.CharField(blank=True, max_length=5)),
                ('complement', models.CharField(blank=True, max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_function', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secundary', 'Secundary')], max_length=9)),
                ('corporate_name', models.CharField(max_length=120)),
                ('fantasy_name', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='companies/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('im', models.CharField(blank=True, max_length=11, unique=True, verbose_name='Inscrição Municipal')),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=20)),
                ('type', models.CharField(blank=True, choices=[('employee', 'Employee'), ('voluntary', 'Voluntary'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/', verbose_name='Photo')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(blank=True, max_length=11, unique=True, verbose_name='CPF')),
                ('andress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.andress', verbose_name='Andress')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
