# Generated by Django 3.2.4 on 2021-07-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='persons/%Y/%m/%d/', verbose_name='Photo'),
        ),
    ]
