# Generated by Django 3.2.4 on 2021-07-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('voluntary', 'Voluntary')], max_length=10),
        ),
    ]
