# Generated by Django 3.2.4 on 2021-07-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_person_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='type',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('employee', 'Employee'), ('voluntary', 'Voluntary'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=10)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.person')),
            ],
        ),
    ]
